// <auto-generated>
//   This file was created to provide strongly-typed access to the Messages.resx resource file.
//   It follows the pattern used by ResXFileCodeGenerator for SDK-style projects.
// </auto-generated>
#nullable enable
using System.Globalization;
using System.Resources;

namespace McpBooking.Server.Properties;

internal static class Messages
{
    private static ResourceManager? s_resourceManager;

    private static ResourceManager ResourceManager =>
        s_resourceManager ??= new ResourceManager(
            "McpBooking.Server.Properties.Messages",
            typeof(Messages).Assembly);

    private static CultureInfo? ResourceCulture { get; set; }

    internal static string ErrorPageInvalid =>
        ResourceManager.GetString("ErrorPageInvalid", ResourceCulture)!;

    internal static string ErrorPerPageInvalid =>
        ResourceManager.GetString("ErrorPerPageInvalid", ResourceCulture)!;

    internal static string ErrorAuthenticationFailed =>
        ResourceManager.GetString("ErrorAuthenticationFailed", ResourceCulture)!;

    internal static string ErrorForbidden =>
        ResourceManager.GetString("ErrorForbidden", ResourceCulture)!;

    internal static string ErrorServerError =>
        ResourceManager.GetString("ErrorServerError", ResourceCulture)!;

    internal static string ErrorApiUnreachable =>
        ResourceManager.GetString("ErrorApiUnreachable", ResourceCulture)!;
}
