// Copyright (c) 2026 RalfGuder. Licensed under the MIT License.
// <auto-generated>
//   This file was created to provide strongly-typed access to the Messages.resx resource file.
//   It follows the pattern used by ResXFileCodeGenerator for SDK-style projects.
// </auto-generated>
#nullable enable
using System.Globalization;
using System.Resources;

namespace McpBooking.Server.Properties;

/// <summary>
/// Provides strongly-typed access to localized message strings defined in Messages.resx.
/// </summary>
internal static class Messages
{
    private static ResourceManager? s_resourceManager;

    /// <summary>
    /// Gets the <see cref="ResourceManager"/> used to look up localized strings.
    /// </summary>
    private static ResourceManager ResourceManager =>
        s_resourceManager ??= new ResourceManager(
            "McpBooking.Server.Properties.Messages",
            typeof(Messages).Assembly);

    /// <summary>
    /// Gets or sets the culture used to retrieve localized strings.
    /// When <see langword="null"/>, the current UI culture is used.
    /// </summary>
    private static CultureInfo? ResourceCulture { get; set; }

    /// <summary>
    /// Gets the error message returned when the page parameter is invalid.
    /// </summary>
    internal static string ErrorPageInvalid =>
        ResourceManager.GetString("ErrorPageInvalid", ResourceCulture)!;

    /// <summary>
    /// Gets the error message returned when the per-page parameter is invalid.
    /// </summary>
    internal static string ErrorPerPageInvalid =>
        ResourceManager.GetString("ErrorPerPageInvalid", ResourceCulture)!;

    /// <summary>
    /// Gets the error message returned when API authentication fails (HTTP 401).
    /// </summary>
    internal static string ErrorAuthenticationFailed =>
        ResourceManager.GetString("ErrorAuthenticationFailed", ResourceCulture)!;

    /// <summary>
    /// Gets the error message returned when access to the API is forbidden (HTTP 403).
    /// </summary>
    internal static string ErrorForbidden =>
        ResourceManager.GetString("ErrorForbidden", ResourceCulture)!;

    /// <summary>
    /// Gets the error message returned when the API responds with a server error (HTTP 5xx).
    /// </summary>
    internal static string ErrorServerError =>
        ResourceManager.GetString("ErrorServerError", ResourceCulture)!;

    /// <summary>
    /// Gets the error message returned when the API cannot be reached.
    /// </summary>
    internal static string ErrorApiUnreachable =>
        ResourceManager.GetString("ErrorApiUnreachable", ResourceCulture)!;
}
